### PR TITLE
Remove Horus dependency and rework user model internals

### PR DESCRIPTION
**Pull request by miohtama**
Prior this pull request Websauna used Horus (https://github.com/Pylons/horus) as a base for user model classes and some minor functionality. However during the year it has become obvious that maintaining the Horus compatibility does not bring too much on the table.

This pull requests remove Horus and drops few other dependency packages.

**There is also a severe breaking change**: the password persistence and hashing algorithm has been updated. Horus was using brcrypt, but currently cryptography scene recommends Argon 2. Argon 2 is now the default using Python's argon2_cffi package.

Due to this

* You need to manually migrate SQL database to new data format 

... or ...

* Just drop the users database table and recreate it with ws-sync-db command (will destroy all users)

I might later provide a script to migrate the data properly, but as far as I know there are no public production use cases for Websauna yet, so I am not going to do it unless somebody asks so with a good reasoning.

### CODE REVIEW

**Comment by enkidulan** [comment]
@miohtama, seems like you've removed pyramid_deform but example from docs still uses it https://github.com/websauna/websauna/edit/master/docs/source/narrative/form/form.rst#L65

**Comment by enkidulan** [comment]
Also docs on https://websauna.org/narrative/form/form.html seems to be not up to date...

**Comment by miohtama** [comment]
Thank you @enkidulan ! I updated docs too, let me see if the website is not up to date.

**Comment by miohtama** [comment]
@enkidulan Fixed in 595d5e41e46b1b9c8181a48319a95de83bfaf810

**Pull request merged**
