### PR TITLE
Pr168 allow using settings in celery configs

### PR DESCRIPTION
**Pull request by petri**
Selected commits from #168 rebased on current master, related to passing settings to celery config parsing only.

### CODE REVIEW

**Comment by ztane** [comment]
Well, just about the commit message; it doesn't now allow the use of `registry`, only `settings` - because of an ordering issue - it is not possible to have registry through all control paths at the time the celery configuration is initialized.

**Comment by ericof** [comment]
Lint tests failed. It seems there is a mix of spaces and tabs in the file

**Comment by petri** [comment]
Ok @ztane @ericof should be fine to merge now.

**Comment by ericof** [comment]
@petri Still failing here https://travis-ci.org/websauna/websauna/jobs/365561591

(Today is under allowed failures, but it will be moved to required soon)

**Pull request merged**
